import './globals.css';
import Header from '../components/layout/header';
import React from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={'antialiased'}>
        <Header />
        <main className="pt-24">{children}</main>
      </body>
    </html>
  );
}
