import './globals.css';
import Header from '../components/layout/header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`antialiased`}>
        <Header />
        <main className="pt-14"></main>
        {children}
      </body>
    </html>
  );
}
